### ISSUE TITLE
Add auto-fixing CRLF linter

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhast#2]
If windows newlines are present, the linter should suggest that they're replaced with unix newlines.

There's two ways to do this:
 - as an AST linter, looking at each node's first token's leading whitespace, and last token's trailing whitespace
 - making a new 'line based linter' which doesn't use the AST at all, but does use the existing linter base classes. This could also be useful for #3

Either way, please make sure the CLI output is clear when running the linter, both in your terminal, and non-interactively (e.g. when redirecting to a file with `> /tmp/somefile`)

**Comment by lexidor** [comment]
@fredemmott can this linter blindly assume that `\r\n` at the end of a line is a mistake?
The `NoWhiteSpaceAtTheendOfLineLinter` does this too, even when inside multiline string literals.
If yes, I'll give this a shot.

**Comment by fredemmott** [comment]
Yep, good point - does NoWhiteSpaceAtTheEndOfLineLinter make this irrelevant?

**Comment by lexidor** [comment]
:thinking: Nope, the whitespace at end of line linter doesn't trip on a `\r\n`, but the newline at end of file linter does.
So people using IDE's (like vscode) that have a `LF <-> CRLF` button can't use a windows line ending, without getting a lint error.
Only those of us who use more raw editors (which allow for multiple line endings in one file) could sneak some `\r\n`s in.

The prio is not real high, but when I do get around to it, would we want to extend the capabilities of the whitespace at end of line linter instead of making a new one?

**Comment by fredemmott** [comment]
This should probably be separate - if we ever support windows, we may want 'No whitespace at end of line, but \r\n is end of line"
