### ISSUE TITLE
Don't report errors caused by 3rd party packages.

### ISSUE THREAD

**Issue by azjezz** [hhvm/hhast#297]
assuming my application implements an interface provided by `vendor/a` package as : 

```hack
namespace App;

use namespace A;

final class Foo implements A\FooInterface {
  public async function bar(): Awaitable<void> {
    // foo things.
  }
}
```

where `A\FooInterface` is as follow: 

```hack
namespace A;

interface FooInterface {
  public function bar(): Awaitable<void>;
}
```

hhast shouldn't report an error on `App\Foo::bar` ( name should be `App\Foo::barAsync` ) and should definitely not fix it since this will break the `FooInterface` contract.

**Comment by azjezz** [comment]
i.e: name convention errors should not be reported on classes where the method is an implementation of an interface.

**Comment by fredemmott** [comment]
We generally suppress these errors explicitly, otherwise it:
- surprises people and makes them think the linter is broken
- removes the benefit of the naming convention: foo() without an await or suppression indicates it’s not async - for codebases using the linter, your example code looks like it’s buggy. Explicit suppression makes it clear it’s not the case

**Comment by fredemmott** [comment]
Also, type system awareness in HHAST must be minimized; the must-use-override linter is already problematic

**Comment by fredemmott** [comment]
An alternative solution is to suggest that users of your library who have this linter enabled create an intermediate class, creating final versions of your declared functions, that delegate to abstract functions with compliant names. That way the suppression is only needed once *and* the majority of user codebases are consistent with the style

**Comment by azjezz** [comment]
Having things work better by default is always best. as I personally don't see the point of having `Async` suffix in async functions, where the type checker already reports on things like : 

```hack
$foo->bar();
```

where foo::bar() is async, one thing I believe could be a solution for us is to have https://github.com/hhvm/hhast/issues/287#issuecomment-629650031, I and @lexidor are already planning a dev tool for @Nuxed which will ship with its own linters, having the ability to disable builtin linters from within our linters would solve this issue.

**Comment by fredemmott** [comment]
We disagree on what is “better” :) the default enforces codebases consistency with builtins and the HSL. Disabling it automatically inherently makes a codebase less internally consistent, assuming it uses the HSL.

**Comment by lexidor** [comment]
> We disagree on what is “better” :)
I side with Fred about many things.
I abide by the AsyncFunctionsAndMethodsLinter, but if the entirety of Nuxed doesn't, I'll help him write something custom.
I don't believe that that belongs in _the_ hhast linters though.

**Comment by azjezz** [comment]
I don't think they do either, but this issue is about something completely different. the case where using any nuxed package ( or any library that doesn't use the `Async` suffix ) causes errors in your application and you are unable to fix them, the only way being disabling them or suppressing the error.

**Comment by fredemmott** [comment]
So, I think you have a somewhat different stance on lint errors:

They are linters because they are optional, and not always best in 100% of cases. Otherwise they would be type errors.

Suppressing a lint error that you choose not to fix (or a library you choose to use intentionally is not compatible with) is not a bad thing. 0 “HH_FIXME”s is a reasonable goal for a project, 0 “HHAST_IGNORE_ERROR” should not be.

**Comment by fredemmott** [comment]
>  any nuxed package ( or any library that doesn't use the Async suffix ) 

The purpose of the linter is to enforce consistency in a project.

If being used in one or two places, suppression is not an overhead. If being used in many places, their codebase is going to be inconsistent anyway, so they should entirely disable the linter (which may be suggested via some conflicts mechanism)

Silently auto-suppressing it /sometimes/ introduces inconsistency, which removes the purpose of the linter. It also has performance problems

**Comment by azjezz** [comment]
> 0 “HH_FIXME”s is a reasonable goal for a project, 0 “HHAST_IGNORE_ERROR” should not be.

Aware, however, adding `HHAST_IGNORE_ERROR` to something which is not an error, and cannot be actually fixed ( the fixed provided by hhast will break the application ), is not a reasonable default.

having to tell hhast to suppress the error when it should know when to do so, is not developer-friendly.

---

Also, promoting is just as bad or worst ( nuxed provides tons of interfaces to implement, having an abstract class to minify the number of `HHAST_IGNORE_ERROR` is not reasonable): 

```hack
namespace App\Http\Handler;

use namespace Nuxed\Contract\Http\{Server, Message}

abstract class Handler implements Server\IHandler {
  public async function handle(
    Message\IServerRequest $request,
  ): Awaitable<Message\IResponse> {
    return await $this->handleAsync($request);
  }

  protected abstract function handleAsync(
    Message\IServerRequest $request,
  ): Awaitable<Message\IResponse>;
}
```

---


> If being used in one or two places, suppression is not a significant problem. If being used in many places, their codebase is going to be inconsistent anyway, so they should entirely disable the linter (which may be suggested via some conflicts mechanism)
> Silently auto-suppressing it /sometimes/ introduces inconsistency, which removes the purpose of the linter. It also has performance problems

HHAST already allows inconsistency, e.g: 

using `await Asio\v()` doesn't report an error, because it's clear that it is not within the developer's power to change that, neither should it report when implementing an interface where it's not within the developer's power to fix it.

**Comment by fredemmott** [comment]
`Asio\v()` should not be used (and should be removed) - `Vec\from_async()` is the replacement which is incompatible.

In general "<x> is not perfect/<other thing> already does <y>" is not persuasive for "HHAST should not care about <x>/HHAST should do <y>".

Also, if implemented, this request seems likely to lead to bad APIs:

```Hack
final class MyClass implements SomeLibraryInterface {
  // required naming to match interface
  public async function foo(): Awaitable<void > {
  }
  // "required" naming to match linter, not an override
  public async function barAsync(): Awaitable<void> {
  }
}
```

This could go further with "disable it for a class that uses any interfaces that violate the linter", but that doesn't solve the problem:
- problem still exists if I use a linter-compliant trait from elsewhere in my project
- it would encourage things using your framework to consistently match your naming; this in itself is not bad. What is bad is combining that with requiring everything else in the app that does not touch your framework to *not* match your naming

The only real fix for this is to say your framework is incompatible with the linter, ideally via some future conflicts mechanism, rather than trying to cut out holes in it.

**Comment by azjezz** [comment]
I believe that's fine as most classes implementing said interface should only have the overriden methods public, and would eventually be called by the framework and not the developer.

The developer would still have the power to disable the linter.

Another thing that would be nice is to have "info" reports, that don't result in exit with code 1, and cannot be fixed by hhast, be still get reported, this way hhast can still report and "info" in this case.

**Comment by fredemmott** [comment]
The expected usage you mention is specific for your library; what if it was a serialization library? Then I would expect it to be one of many public methods on most objects using the interface.

—- 

Very open to a severity level being added (and configurable per linter in hhast-lint.json)

Would also need:
- configuration option for the non-zero exit
- configuration option to only report in modified files (at least in LSP mode - ideally pluggable to support git status etc)

Those could default to exit 0 and “open files/git status only”, as long as there remains an easy way for people to audit for them in their CI jobs and still ban them completely.
